add validate-only option (#14)
* add validate-only option

* convert tabs to spaces

* error early if validation requested and without java present

diff --git a/pdf2archive b/pdf2archive
--- a/pdf2archive
+++ b/pdf2archive
@@ -75,6 +75,8 @@ OPTIONS:
                       specified via the command line options.
   --validate          Validate  the resulting file. The  validation is done with
                       VeraPDF, you need a working Java installation.
+  --validate-only     Perform only the validation on the input file, again using
+                      VeraPDF
   --debug             Write additional debug information on screen
   -v, --version       Show the program version
 
@@ -104,6 +106,21 @@ if [ "$(which gs)" == "" ]; then
     exit
 fi
 
+#=====# VALIDATION #=====#
+
+javaCheck() {
+    if [ "$(which java)" == "" ]; then
+        echo "  ERROR: Java is not installed or it's not in the path"
+        echo "  Cannot perform validation"
+        exit 1
+    fi
+}
+
+validate() {
+    javaCheck
+    echo "  Validating..."
+    echo "  $(./verapdf/verapdf "$1" --extract --flavour 1b --format text "$2")"
+}
 
 #=====# INPUT PARSER #=====#
 if [ "$1" == "" ]; then
@@ -165,11 +182,12 @@ while [ "$1" != "" ]; do
             PDFKEYWORDS=$VALUE
             ;;
         --validate)
-            if [ "$(which java)" == "" ]; then
-                echo "  ERROR: Java is not installed or it's not in the path"
-                exit 1
-            fi
+            javaCheck
             VALIDATE=true
+            ;;
+        --validate-only)
+            validate $VERAMSGOPTS $2
+            exit
             ;;
         *.pdf)
             if [ "$INPUT" == "" ]; then
@@ -190,7 +208,6 @@ while [ "$1" != "" ]; do
     esac
     shift
 done
-
 
 #=====# SET UP ALL THE STUFF #=====#
 echo "=== Welcome to PDF2ARCHIVE ==="
@@ -361,8 +378,7 @@ echo "  Done, now ESSE3 is happy! ;)"
 
 #=====# VALIDATE THE RESULT #=====#
 if $VALIDATE; then
-    echo "  Validating resulting file..."
-    echo "  $(./verapdf/verapdf $VERAMSGOPTS --extract --flavour 1b --format text $OUTPUT)"
+    validate $VERAMSGOPTS $OUTPUT
 else
     echo "  Suggestion: validate the resulting PDF to be sure it's PDF/A-1B compliant."
 fi
